<nav>
	<p><a href="index.php">Home</a></p>
	<p><a href="cadastro_cliente.php">Cadastrar cliente</a></p>
	<p><a href="cadastro_produto.php">Cadastrar produto</a></p>
	<p><a href="vendas_produtos.php">Vendas de Produtos</a></p>
    <p><a href="lista_cliente.php">Mostrar clientes</a></p>
    <p><a href="lista_produtos.php">Mostrar produtos</a></p>
    <p><a href="lista_vendas.php">Mostrar vendas</a></p>
</nav>