-- consultas selct- 08/05

SELECT CPF, NOME, SALARIO
FROM FUNCIONARIO;

SELECT DNUMERO, DNOME
FROM DEPARTAMENTO;

SELECT PROJNUMERO, PROJNOME, DNUMERO
FROM PROJETO;

SELECT * FROM FUNCIONARIO;

SELECT * FROM DEPARTAMENTO;


SELECT CPF, NOME, SALARIO, DNUMERO
FROM FUNCIONARIO
WHERE DNUMERO <> 5;

select CPF, NOME, SALARIO, DNUMERO
FROM FUNCIONARIO;

SELECT CPF, NOME, SALARIO, DNUMERO
FROM FUNCIONARIO
WHERE SALARIO <= 4000;

SELECT *
FROM FUNCIONARIO
WHERE ESTADO = 'SP';

SELECT *
FROM FUNCIONARIO
WHERE SALARIO > 3500;

SELECT DNUMERO
FROM DEPARTAMENTO
WHERE DNOME = 'PESQUISA';

SELECT * FROM DEPARTAMENTO;

----------------------- ORDER BY (DECRECENTE E CRESCENTE)


SELECT NOME, SALARIO
FROM FUNCIONARIO
ORDER BY SALARIO ASC;

SELECT * 
FROM FUNCIONARIO
ORDER BY DATANASC DESC;

SELECT * 
FROM FUNCIONARIO
WHERE DATANASC;

SELECT NOME, DNUMERO, SALARIO
FROM FUNCIONARIO
ORDER BY DNUMERO ASC, SALARIO DESC;

----------------------- DISTINCT (FEMININO E MASCULINO)


SELECT DNUMERO
FROM FUNCIONARIO
WHERE SEXO = 'M';


SELECT DISTINCT SALARIO
FROM FUNCIONARIO
WHERE SEXO = 'F';

SELECT DISTINCT BAIRRO
FROM FUNCIONARIO
WHERE CIDADE = 'São Paulo';

----------------------- OPERADOR LIKE (CONSUTA EM PARTES DA STRING)

SELECT NOME, DATANASC, CEP
FROM FUNCIONARIO
WHERE CEP LIKE '12345%';
