<!DOCTYPE html>
<html lang="pt-BR">
	<head>
		<meta charset="utf-8"/>
	</head>
	<body>
		<nav style="float: left; max-width:160px;
					padding: 1em;
					background-color:Lightgray;">
			<ul>
					<li><a href="index.php">Pagina Inicial</a></li>
				<br>
					Cliente:
						<small>
							<li><a href="form_cadastro_cliente.php">Cadastrar Cliente</a></li>
							<li><a href="lista_clientes.php">Listar Clientes</a></li>
						</small>
				<br>
					Psicologos:
						<small>
							<li><a href="form_cadastro_psico.php">Cadastrar Psicologos</a></li>
							<li><a href="lista_psico.php">Listar Psicologos</a></li>
						</small>
				<br>
					Consultas:
						<small>
							<li><a href="form_cadastro_consulta.php">Agendar Consulta</a></li>
							<li><a href="lista_consulta.php">Consultar Agenda</a></li>
						</small>
				<br>
				<br>
					<li><a href="form_cadastro_contato.php">Fale Conosco</a></li>
			</ul>
		</nav>
	</body>
</html>