<nav>
	<p><a href="index.php"></a>Home</p>
	<p><a href="form_cadastro_cliente.php">Cadastrar Cliente</a></p>
	<p><a href="form_cadastro_produto.php">Cadastrar Produto</a></p>
	<p><a href="form_venda_produto.php">Venda de Produtos</a></p>
	<p><a href="lista_clientes.php">Listar Clientes</a></p>
	<p><a href="lista_produtos.php">Listar Produtos</a></p>
	<p><a href="lista_vendas.php">Listar Vendas</a></p>
</nav>