<form action="index.php" method="POST">
    <fieldset>
        <legend> Cadastro de livros</legend>
            <p>
                <label>Nome</label>
                <input type="text" name="nome" />
            </p> 

            <p>      
                <label>Prova 1</label>
                <input type="text" name="n1" />
            </p>

            <p>
                <label>Prova 2</label>
                <input type="text" name="n2" />
            </p>
	
            <p>
               <input type="submit" value="cadastrar"/>
             </p>
    </fieldset>
</form>