<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="utf-8"/>
	<title>Cadastro de Produto</title>
</head>
<body>
	<article>
		<form action="form_cadastro_produto.php" method="POST">
			<fieldset>
				<legend> Cadastro de Produto</legend>
				<p>
					<label>Código:</label>
						<input type="text" name="cod" size="30"/>
				</p>
				<p>
					<label>Descrição:</label>
						<input type="text" name="des" size="27"/>
				</p>
				<p>
					<label>Preço:</label>
						<input type="text" name="preco" size="31"/>
						
				<p><input type="submit" value="Cadastrar Produto"/></p>
			</fieldset>
		<form>
		<br>	<br>	<br>
	</article>
</body>
</html>