<article>
    <h3>Cadastro de novo cliente</h3>
    <br/>

    <form action="form_cadastro_produto.php" method="POST">
        <p>
            <label>Codigo:</label>
            <input type="text" name="codigo"/>
        </p>
        <p>
            <label>Descrição:</label>
            <input type="text" name="descricao"/>
        </p>
        <p>
             <label>Preço:</label>
             <input type="number" name="preco"/>
         </p>
        
        <p>
                <label></label>
                <input type="submit" name="Cadastrar Produto"/>
            </p>
    </form>
</article>