<nav>
    <p><a href="index.php">Home</a></p>
    <p><a href="form_cadastro_cliente.php">Cadastrar Clientes</a></p> 
    <p><a href="form_cadastro_produto.php">Cadastrar Produtos</a></p>  
    <p><a href="form_venda_produto.php">Venda de Produtos</a></p>  
    <p><a href="lista_clientes.php">Lista de Cliente</a></p> 
    <p><a href="lista_produtos.php">Lista de Produto</a></p> 
    <p><a href="lista_vendas.php">Lista de Vendas</a></p>    
</nav>