<article>
    <h3>cadastro de novo produto</h3>
    <br/>
    <form action="form_cadastro_produto.php" method="POST">
        <p>
            <label>codigo:</label>
            <input type="text" name="codigo"/>
        </p>

        <p>
            <label>descriçao:</label>
            <input type="text" name="descricao"/>
        </p>

        <p>
            <label>preço:</label>
            <input type="number" name="preco"/>
       </p>
        <p>
           <label></label>
            <input type="submit" value= "cadastrar cliente"/>
       </p>
    
   </form>
</article>