<nav>
    <p><a href="index.php">home</a></p>
    <p><a href="form_cadastro_cliente.php">cadastrar cliente</a></p>
    <p><a href="form_cadastro_produto.php">cadastrar produto</a></p>
    <p><a href="form_venda_produtos.php">venda de produtos</a></p>
    <p><a href="lista_clientes.php">lista clientes</a></p>
    <p><a href="lista_produtos.php">lista produtos</a></p>
    <p><a href="lista_vendas.php">lista vendas</a></p>
</nav>