<nav style="float: left; max-width:160px;
			padding: 1em;
			background-color:Lightgray;">
	<ul>
		<li><a href="index.php">Home</a></li>
		<li><a href="form_cadastro_cliente.php">Cadastro de Clientes</a></li>
		<li><a href="form_cadastro_produto.php">Cadastro de Produtos</a></li>
		<li><a href="form_venda_produtos.php">Venda de Produtos</a></li>
		<li><a href="lista_clientes.php">Lista de Clientes</a></li>
		<li><a href="lista_produtos.php">Lista de Produtos</a></li>
		<li><a href="lista_vendas.php">Lista de Vendas</a></li>
	</ul>
</nav>